package com.asiacell.billing.undertest;

import javax.swing.*;
import java.io.*;
public class FileChooserDemo_1 extends javax.swing.JFrame {
    
    /** Creates new form NewJFrame */
    public FileChooserDemo_1() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cmdBrowse = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();
        cmdExit = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FileChooserTest");
        setResizable(false);
        cmdBrowse.setText("Browse");
        cmdBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowseActionPerformed(evt);
            }
        });

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Verdana", 1, 12));
        txtDisplay.setForeground(new java.awt.Color(0, 0, 153));
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        cmdClear.setText("Clear");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdBrowse, cmdClear, cmdExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBrowse)
                    .addComponent(cmdClear)
                    .addComponent(cmdExit))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdBrowse, cmdClear, cmdExit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
    txtDisplay.setText("");  
    }//GEN-LAST:event_cmdClearActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_cmdExitActionPerformed

    private void cmdBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowseActionPerformed
    JFileChooser fc = new JFileChooser();
    File currentDir = new File("c:\\");
    fc.setCurrentDirectory(currentDir);   
    int retValue = fc.showDialog(null,"Upload a rate sheet");
    String filename = fc.getName(fc.getSelectedFile());
    String tempPath = fc.getName(fc.getCurrentDirectory());
    String fullPath = "";        
    //String fullPath = dirname;
    while (! tempPath.endsWith(":)"))
    {
        fullPath = tempPath + "\\" + fullPath;
        fc.changeToParentDirectory();
        tempPath = fc.getName(fc.getCurrentDirectory());
    }
    //tempPath = tempPath.substring(0,tempPath.length() - 1);
    fullPath = fc.getName(fc.getCurrentDirectory()).substring(tempPath.indexOf(":") - 1,tempPath.indexOf(":") + 1) + "\\" + fullPath + filename;    
    //System.out.println(fullPath);
    if (retValue == 0)
        txtDisplay.setText(fullPath);
    else
        txtDisplay.setText("No file choosed");
    }//GEN-LAST:event_cmdBrowseActionPerformed
    
    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[])
    throws Exception{
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooserDemo().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdExit;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
    
}
