package com.asiacell.billing.prm.idd;

import javax.swing.UIManager;
import javax.swing.*;
import java.io.*;
/*
 * GlobeConvertGUI.java
 *
 * Created on October 9, 2007, 11:23 PM
 */

/**
 *
 * @author  hasanein.ali
 */
public class GlobeConvertGUI extends javax.swing.JFrame implements Runnable {
    
    /** Creates new form GlobeConvertGUI */    
    public GlobeConvertGUI() {
        initComponents();                  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        lblSourceFile = new javax.swing.JLabel();
        lblDestFile = new javax.swing.JLabel();
        txtSourceFile = new javax.swing.JTextField();
        txtDestFile = new javax.swing.JTextField();
        cmdBrowse = new javax.swing.JButton();
        cmdConvert = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDisplay = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cmdClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Globecom Rate Format Converter");
        setResizable(false);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\documents\\My Pictures\\3D\\3D (18).jpg"));

        lblSourceFile.setText("Source File to Convert");

        lblDestFile.setText("Destination Output File");

        cmdBrowse.setText("Browse");
        cmdBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowseActionPerformed(evt);
            }
        });

        cmdConvert.setText("Convert");
        cmdConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConvertActionPerformed(evt);
            }
        });

        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        txtaDisplay.setColumns(20);
        txtaDisplay.setEditable(false);
        txtaDisplay.setFont(new java.awt.Font("Courier New", 0, 12));
        txtaDisplay.setRows(5);
        txtaDisplay.setOpaque(false);
        jScrollPane1.setViewportView(txtaDisplay);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("e.g. D:\\output.txt");

        cmdClear.setText("Clear");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cmdConvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDestFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDestFile)
                            .addComponent(txtSourceFile, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdBrowse))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdClear, cmdConvert, cmdExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSourceFile)
                    .addComponent(txtSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDestFile)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDestFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdConvert)
                    .addComponent(cmdClear)
                    .addComponent(cmdExit))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdConvert, cmdExit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
    txtDestFile.setText("");
    txtSourceFile.setText("");
    txtaDisplay.setText("");
    }//GEN-LAST:event_cmdClearActionPerformed

    private void cmdConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConvertActionPerformed
    cmdConvert.setEnabled(false);
    cmdClear.setEnabled(false);
    Thread t = new Thread(this);
    t.start();    
    }//GEN-LAST:event_cmdConvertActionPerformed

    public void run()
    {
        String sourceFile = txtSourceFile.getText();
        String destFile = txtDestFile.getText();
        String myText = "";
        for (int i=0;i<1000;i++)
        {
            myText = myText + sourceFile + " Converted" + '\n';
            txtaDisplay.setText(myText);
        }
        cmdConvert.setEnabled(true);
        cmdClear.setEnabled(true);
        JOptionPane.showMessageDialog(null,"Convert Completed");
    }
    
    private void cmdBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowseActionPerformed
    JFileChooser fc = new JFileChooser();
    File currentDir = new File("d:\\");
    fc.setCurrentDirectory(currentDir);
    int retValue = fc.showDialog(null,"Choose a file");
    if (retValue == 0)
    {
        File selectedFile = fc.getSelectedFile();
        String filePath = selectedFile.toString();
        txtSourceFile.setText(filePath);
    }
    else
        JOptionPane.showMessageDialog(null,"Please select a source file to be converted");
    }//GEN-LAST:event_cmdBrowseActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_cmdExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
        throws Exception{
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlobeConvertGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdConvert;
    private javax.swing.JButton cmdExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDestFile;
    private javax.swing.JLabel lblSourceFile;
    private javax.swing.JTextField txtDestFile;
    private javax.swing.JTextField txtSourceFile;
    private javax.swing.JTextArea txtaDisplay;
    // End of variables declaration//GEN-END:variables

}
